In [3]:
line = "the entire movie is filled with deja vu moments ."
tokens = line.split()
print(tokens)
print(type(tokens))

['the', 'entire', 'movie', 'is', 'filled', 'with', 'deja', 'vu', 'moments', '.']
<class 'list'>


In [4]:
sentence = " ".join(tokens)
print(sentence)
print(type(sentence))

the entire movie is filled with deja vu moments .
<class 'str'>


In [1]:
import torch

In [2]:
y_data = [3, 1, 2, 3, 2]
labals = torch.LongTensor(y_data)
print(labals)

tensor([3, 1, 2, 3, 2])


In [3]:
from sklearn.preprocessing import LabelEncoder

In [5]:
encoder = LabelEncoder()
encoder.fit(y_data)
y = encoder.transform(y_data)
labals = torch.LongTensor(y)
print(labals.size())
print(labals)

torch.Size([5])
tensor([2, 0, 1, 2, 1])


In [1]:
import gensim
embedding = 'embed/GoogleNews-vectors-negative300.bin'
model = gensim.models.KeyedVectors.load_word2vec_format(embedding, binary=True)

In [7]:
import torch
from torch.distributions import uniform

In [16]:
word1 = model[',']
# word2 = uniform.Uniform(-0.25, 0.25).sample(torch.Size([300]))
print(word1)
# print(word2)

KeyError: "word ',' not in vocabulary"

In [2]:
import numpy as np

In [3]:
value = 256
input_x = np.random.randn(1,value,value,3)
input_y = np.random.randn(1,1,1,3)
input_pow = 2

In [4]:
x_shape = np.shape(input_x)
y_shape = np.shape(input_y)
print(x_shape)
print(y_shape)

(1, 256, 256, 3)
(1, 1, 1, 3)


In [7]:
x = np.reshape(input_x,(-1,y_shape[-1]))
x_new_shape = np.shape(x)
print(x_new_shape)

(65536, 3)


In [12]:
def power_diff_numpy(input_x,input_y,input_z):
    x_shape = np.shape(input_x)
    y_shape = np.shape(input_y)
    x = np.reshape(input_x,(-1, y_shape[-1]))
    x_new_shape = np.shape(x)
    y = np.reshape(input_y,(-1))
    output = []
    for i in range(x_new_shape[0]):
        tmp1 = tmp2 = x[i]-y
        for j in range(input_z-1):
            tmp1 = tmp1*tmp2
        output.append(tmp1)
    output = np.reshape(output,x_shape)
    return output

In [13]:
output = power_diff_numpy(input_x, input_y, 2)
print(output)

[[[[2.20741712e+00 2.75855852e+00 5.95146838e-01]
   [8.40717772e-01 2.99419050e-03 1.08263391e-01]
   [7.97250495e+00 6.69358725e-01 1.03383411e+00]
   ...
   [3.25361512e-01 3.42670060e+00 4.16250370e+00]
   [1.64057150e+00 1.24477758e+00 1.53783977e+00]
   [2.54592127e+00 1.46539147e-01 5.84423878e+00]]

  [[9.96560299e-01 4.28190670e-02 3.96190953e-01]
   [1.11153105e+00 9.39519453e+00 2.51459216e+00]
   [1.69867725e+00 5.34835446e-01 1.64771723e+01]
   ...
   [7.18079931e+00 5.76188445e-01 1.49750257e-01]
   [7.41225963e+00 4.37751407e-03 1.16130308e+00]
   [3.42974986e-01 7.06249214e-01 3.65737291e-02]]

  [[2.08447086e+00 3.03062919e-04 4.22950889e+00]
   [3.40636392e+00 7.72222598e-01 8.31446614e-01]
   [1.04916421e+00 9.83069444e-03 1.45029822e+00]
   ...
   [1.74915279e+00 3.82744817e-02 4.68411229e-01]
   [3.26223997e+00 2.78888357e-01 2.51275116e+00]
   [1.52294583e+00 2.80451700e-01 7.02686210e+00]]

  ...

  [[1.31700465e+00 1.04575820e-01 3.01278347e+00]
   [6.78104960e+